@startmindmap

+ tugas-praktikum-c-sabtu
++ tugas-1
+++_ tugas-mandiri-1.cpp
+++_ tugas-mandiri-2.cpp
+++_ tugas-mandiri-n.cpp
++ tugas-2
+++_ tugas-mandiri-1.cpp
+++_ tugas-mandiri-2.cpp
+++_ tugas-mandiri-n.cpp
++ tugas-3
+++_ tugas-mandiri-1.cpp
+++_ tugas-mandiri-2.cpp
+++_ tugas-mandiri-n.cpp
++ tugas-n
@endmindmap